### ISSUE TITLE
Demonstration data link is invalid

### ISSUE THREAD

**Issue by lywlywlywlyw** [kristery/dex-affordance#3]
Hi Yueh-Hua,

Thanks for providing the outstanding project code.
It seems that the demonstration data can't be downloaded by "sh ./download.sh".The error is below:
--------------------------------------------------------------------------------------
 $sh ./download.sh
/home/lyw/miniconda3/envs/ilad/lib/python3.8/site-packages/gdown/__main__.py:132: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Failed to retrieve file url:

        Cannot retrieve the public link of the file. You may need to change
        the permission to 'Anyone with the link', or have had many accesses.
        Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

        https://drive.google.com/uc?id=1h839ThfpELnj6cMQye3uI_hTxw4zHg5s

but Gdown can't. Please check connections and permissions.
/home/lyw/miniconda3/envs/ilad/lib/python3.8/site-packages/gdown/__main__.py:132: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Failed to retrieve file url:

        Cannot retrieve the public link of the file. You may need to change
        the permission to 'Anyone with the link', or have had many accesses.
        Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

        https://drive.google.com/uc?id=1k1jkFgdbJl0aox4F6CUFpdokRZbo6Ug_

but Gdown can't. Please check connections and permissions.
/home/lyw/miniconda3/envs/ilad/lib/python3.8/site-packages/gdown/__main__.py:132: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Failed to retrieve file url:

        Cannot retrieve the public link of the file. You may need to change
        the permission to 'Anyone with the link', or have had many accesses.
        Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

        https://drive.google.com/uc?id=145lwDp42gmiaPOkEKSBkQGkySnDDe6YW

but Gdown can't. Please check connections and permissions.
/home/lyw/miniconda3/envs/ilad/lib/python3.8/site-packages/gdown/__main__.py:132: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Failed to retrieve file url:

        Cannot retrieve the public link of the file. You may need to change
        the permission to 'Anyone with the link', or have had many accesses.
        Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

        https://drive.google.com/uc?id=1D6F9vfohJgLd_WQdd5bI2TH5f0TTg24t

but Gdown can't. Please check connections and permissions.
/home/lyw/miniconda3/envs/ilad/lib/python3.8/site-packages/gdown/__main__.py:132: FutureWarning: Option `--id` was deprecated in version 4.3.1 and will be removed in 5.0. You don't need to pass it anymore to use a file ID.
  warnings.warn(
Failed to retrieve file url:

        Cannot retrieve the public link of the file. You may need to change
        the permission to 'Anyone with the link', or have had many accesses.
        Check FAQ in https://github.com/wkentaro/gdown?tab=readme-ov-file#faq.

You may still be able to access the file from the browser:

        https://drive.google.com/uc?id=1OjrK3cIVDtLQJovrIc03Bj8SW2o27UIQ

but Gdown can't. Please check connections and permissions.
--------------------------------------------------------------------------------
I tried to download demonstration data through the URL above,but I got 404 exception from the browser.I guess the download link is overdue.Could you please provide a new demonstration data link or a new download.sh file?
My google email address is yuwanliu06@gmail.com.
Best,
lywlywlywlyw

**Comment by kristery** [comment]
Hi lywlywlywlyw,

Thank you for your feedback! Please use the following link to download the demonstrations https://drive.google.com/drive/folders/1I5WgQ5pT6URRp8NgwZ26LOzIAI67KmLX?usp=sharing

**Comment by lywlywlywlyw** [comment]
Hi Yueh-Hua,
Thank you for your demonstration data and your excellent work, we have benefited a lot from it.
Best,
lywlywlywlyw
